baseURL: 'https://blog.mosuke.tech'
languageCode: ja
title: Goldstine研究所
theme: mosuke-tech-hugo-theme
Paginate: 10
hasCJKLanguage: true
disqusShortname: mosuke5-techblog
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: categories
      weight: 100
permalinks: {}
params:
  hideShareOptions: true
  description: '@mosuke5のブログサイト。クラウド技術やアプリ開発、インフラ系ツールなどを主に情報発信しています。'
  google_analytics: UA-99596316-1
  google_ad: ca-pub-2753210161325997
  contactUrl: >-
    https://docs.google.com/forms/d/e/1FAIpQLSd6N53H7zfF8EBrvyezRizU1mQx-CP3vc_jG-WvxfRmCjHTpg/viewform
  twitter: '@mosuke5'
  bing_webmaster: 9220008783970B337CA4AE8362168354
  google_site_verification: OcOuGmjhG050c1d16ySxY_FCLT4zhvxFEsGLD9mm6f0
  openshift_ad: true
taxonomies:
  category: categories
  archive: archive
markup:
  goldmark:
    extentions:
      linkify: false
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
