baseURL = "https://blog.mosuke.tech"
languageCode = "ja"
title = "Goldstine研究所(仮)"
theme = "purehugo"
Paginate = 10

[permalinks]
#entry = "/entry/:year/:month/:day/:filename"

[params]
profileSite = "https://mosuke.tech"
hideShareOptions = true
description = "mosuke5's blog"

[taxonomies]
tag = "tags"
category = "categories"
archive = "archive"
