baseURL = "https://blog.mosuke.tech"
languageCode = "ja"
title = "Goldstine研究所(仮)"
theme = "purehugo"
Paginate = 10

[permalinks]
post = "/entry/:year/:month/:day/:filename"

[params]
profileSite = "https://mosuke.tech"
hideShareOptions = true
description = "mosuke5's tech blog"
