baseURL = "https://blog.mosuke.tech"
languageCode = "ja"
title = "Goldstine研究所"
theme = "purehugo"
Paginate = 10
hasCJKLanguage = true
disqusShortname = "mosuke5-techblog"

[permalinks]
#entry = "/entry/:year/:month/:day/:filename"

[params]
profileSite = "https://mosuke.tech"
hideShareOptions = true
subTitle = "@mosuke5's Blog"
description = "@mosuke5のブログサイト。クラウド技術やアプリ開発、インフラ系ツールなどを主に情報発信しています。"
google_analytics = "UA-99596316-1"

[taxonomies]
category = "categories"
archive = "archive"

#disableKinds = ["tags"]