name: deploy
on:
  push:
    branches:
      - debug
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone blog contentes
        uses: actions/checkout@v3

      - name: Git clone blog theme
        uses: actions/checkout@v3
        with:
          repository: mosuke5/mosuke-tech-hugo-theme
          path: themes/mosuke-tech-hugo-theme
          ref: 92be2b0c9f111a187795c4aa329ba89187b4ed14

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'

      - name: Build
        run: hugo

      - name: debug
        run: git log
      
      - run: echo ${{GITHUB_SHA}}
      - run: env

      - name: Purge cloudflare cache
        run: |
          bash ./scripts/delete_page_cache.sh ${{secrets.CF_ZONE_ID}} ${{secrets.CF_EMAIL}} ${{secrets.CF_KEY}}
