name: deploy
on:
  workflow_run:
    workflows: ["test"]
    branches:
      - main
    types:
      - completed
  schedule:
    - cron: '0 23 * * *' # 8:00 JST
env:
  TZ: 'Asia/Tokyo'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Git clone blog contentes
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.152.2'

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'schedule' }}
        with:
          external_repository: mosuke5-lab/mosuke5-lab.github.io
          publish_branch: main
          publish_dir: ./public
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          cname: blog.mosuke.tech

      - name: Purge cloudflare cache
        run: |
          bash ./scripts/delete_page_cache.sh ${{secrets.CF_ZONE_ID}} ${{secrets.CF_EMAIL}} ${{secrets.CF_KEY}}
